name: Docker

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      FORGEJO_USER: ${{ secrets.FORGEJO_USER }}
      FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Build image
        run: |
          nix store gc --extra-experimental-features 'nix-command flakes'
          nix build .#dockerImage --accept-flake-config --fallback --extra-experimental-features 'nix-command flakes'
      - name: Set tag
        run: echo "IMAGE_TAG=$([ "${{ forgejo.event_name }}" = workflow_dispatch ] && echo latest || echo ${{ forgejo.ref_name }})" >> "$GITHUB_ENV"
      - name: Push to Forgejo registry
        run: |
          mkdir -p /etc/containers
          echo '{"default":[{"type":"insecureAcceptAnything"}]}' > /etc/containers/policy.json
          nix shell nixpkgs#skopeo --extra-experimental-features 'nix-command flakes' -c \
            skopeo copy docker-archive:result \
            "docker://forgejo.sakul-flee.de/sakulflee/fansly-recorder:${IMAGE_TAG}" \
            --dest-creds="$FORGEJO_USER:$FORGEJO_TOKEN"
