when:
  event: [tag, manual]
  branch: main

steps:
  build-and-push:
    image: nixos/nix:latest
    commands:
      - nix build .#dockerImage --accept-flake-config --extra-experimental-features 'nix-command flakes'
      - mkdir -p /etc/containers && echo '{"default":[{"type":"insecureAcceptAnything"}]}' > /etc/containers/policy.json
      - nix shell nixpkgs#skopeo --extra-experimental-features 'nix-command flakes' -c skopeo copy docker-archive:result docker://forgejo.sakul-flee.de/sakulflee/fansly-recorder:${CI_COMMIT_TAG:-latest} --dest-creds="$FORGEJO_USERNAME:$FORGEJO_PASSWORD"
    environment:
      FORGEJO_USERNAME:
        from_secret: FORGEJO_USERNAME
      FORGEJO_PASSWORD:
        from_secret: FORGEJO_PASSWORD
