when:
  event: [tag, manual]
  branch: main

steps:
  build-and-push:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: forgejo.sakul-flee.de
      repo: sakulflee/fansly-recorder
      tags:
        - ${CI_COMMIT_TAG:-latest}
      dockerfile: Dockerfile
      username:
        from_secret: forgejo_user
      password:
        from_secret: forgejo_token
