when:
  event: [tag, manual]
  branch: main

steps:
  build-and-push:
    image: nixos/nix:latest
    commands:
      - nix store gc --extra-experimental-features 'nix-command flakes'
      - nix build .#dockerImage --accept-flake-config --fallback --extra-experimental-features 'nix-command flakes'
      - mkdir -p /etc/containers ~/.docker && echo '{"default":[{"type":"insecureAcceptAnything"}]}' > /etc/containers/policy.json
      - echo "{\"auths\":{\"forgejo.sakul-flee.de\":{\"auth\":\"$(echo -n $FORGEJO_USER:$FORGEJO_TOKEN | base64 -w0)\"}}}" > ~/.docker/config.json
      - nix shell nixpkgs#skopeo --extra-experimental-features 'nix-command flakes' -c skopeo copy docker-archive:result docker://forgejo.sakul-flee.de/sakulflee/fansly-recorder:${CI_COMMIT_TAG:-latest}
    environment:
      FORGEJO_USER:
        from_secret: forgejo_user
      FORGEJO_TOKEN:
        from_secret: forgejo_token
